// 此文件由 script/downLoadIcon.js 自动生成
export const ICON_TYPES = [
  "icon-issue",
  "icon-xingxingzuhe",
  "icon-dianzan1",
  "icon-diancai",
  "icon-a-bianzubeifen3",
  "icon-a-duihuacishubeifen8",
  "icon-wendapinglun",
  "icon-toupiaofankui",
  "icon-AIrunse",
  "icon-Koala-zhengfangxing-heise",
  "icon-taolunqu",
  "icon-wendang",
  "icon-pinglun",
  "icon-xiaoxi",
  "icon-iconfontgerenzhongxin",
  "icon-guanbi-fill",
  "icon-tuichu",
  "icon-shangchuan",
  "icon-tanhao",
  "icon-duihao",
  "icon-weixie",
  "icon-anquan",
  "icon-keyi",
  "icon-weizhi",
  "icon-fankui",
  "icon-github",
  "icon-wendadui-moren",
  "icon-zaixianwangye-moren",
  "icon-tongyongwendang-xuanzhong",
  "icon-wendadui-xuanzhong",
  "icon-tongyongwendang-moren",
  "icon-zaixianwangye-xuanzhong",
  "icon-zhishiku-xuanzhong",
  "icon-zhishiku-moren"
] as const;
export type IconType = (typeof ICON_TYPES)[number];
